// Generated by dojo-bindgen on Thu, 5 Sep 2024 16:48:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `brewmaster::models::manager::MaxScale` model
public class MaxScale : ModelInstance {
    [ModelField("system")]
    public FieldElement system;

    [ModelField("maxTable")]
    public ushort maxTable;

    [ModelField("maxStool")]
    public ushort maxStool;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        