// Generated by dojo-bindgen on Thu, 5 Sep 2024 16:48:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `brewmaster::models::manager::SystemManager` model
public class SystemManager : ModelInstance {
    [ModelField("system")]
    public FieldElement system;

    [ModelField("managerAddress")]
    public FieldElement managerAddress;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        